# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDD9D6
background         #121318
cursor             #FDD9D6

active_tab_foreground     #121318
active_tab_background     #FDD9D6
inactive_tab_foreground   #FDD9D6
inactive_tab_background   #121318

active_border_color   #FDD9D6
inactive_border_color #121318
bell_border_color     #3E3053

color0      #3A3B40
color1		#3E3053
color2		#14416B
color3		#722633
color4		#1E68A5
color5		#2274B8
color6		#BB6E68
color7		#F4C0BD
color8		#AA8684
color9		#53406F
color10		#1B578F
color11		#983244
color12		#288ADB
color13		#2D9BF5
color14		#F9928B
color15		#F4C0BD
